In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn import metrics

# Import Dataset

In [9]:
data=pd.read_table('C:\MY DRIVE\Personal\dataset\All_Data\All_Data\P004.txt')

In [10]:
data.head()

,CurrentMilk,Previous,Fat,Protein,Days,Lactation,I79
0,45,45,5.5,8.9,21,5,0
1,86,86,4.4,4.1,25,4,0
2,50,50,6.5,4.0,25,7,0
3,42,42,7.4,4.1,25,2,0
4,61,61,3.8,3.8,33,2,0


In [11]:
X=data.iloc[:,:-1]

In [12]:
X.head()

,CurrentMilk,Previous,Fat,Protein,Days,Lactation
0,45,45,5.5,8.9,21,5
1,86,86,4.4,4.1,25,4
2,50,50,6.5,4.0,25,7
3,42,42,7.4,4.1,25,2
4,61,61,3.8,3.8,33,2


# One-hot encoding

In [13]:
# Sample dataframe
#data = {'dependent': ['lactate','notlactate']}

# Apply one-hot encoding
encoded_df = pd.get_dummies(data, columns=['I79'], dtype=int)

print(encoded_df)

     CurrentMilk  Previous  Fat  Protein  Days  Lactation  I79_0  I79_1
0             45        45  5.5      8.9    21          5      1      0
1             86        86  4.4      4.1    25          4      1      0
2             50        50  6.5      4.0    25          7      1      0
3             42        42  7.4      4.1    25          2      1      0
4             61        61  3.8      3.8    33          2      1      0
..           ...       ...  ...      ...   ...        ...    ...    ...
194           89        89  3.3      3.0   149          2      0      1
195           68        69  3.5      3.4   149          2      0      1
196           55        54  5.9      3.4   149          1      0      1
197           47        57  3.5      2.9   149          2      0      1
198           73        61  3.6      2.8   151          1      0      1

[199 rows x 8 columns]


# Model for not lactation

In [46]:
model1=LinearRegression()
model1.fit(X, encoded_df['I79_0'])

LinearRegression()

# Model for lactation

In [47]:
model2=LinearRegression()
model2.fit(X, encoded_df['I79_1'])

LinearRegression()

In [48]:
x=np.array([45,45,5.0,8.9,21,5]).reshape(1,-1)

In [49]:
np.array([45,45,5.0,8.9,21,5]).shape

(6,)

In [50]:
#x.reshape(1,6)

# Value of discriminant function(not lactating)

In [51]:
model1.predict(x)

c:\my drive\research work2\coding\env\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1.10447138])

# Value of discriminant function(lactating)

In [52]:
model2.predict(x)

c:\my drive\research work2\coding\env\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-0.10447138])

###  The value of not lactating function is more than lactating, therefore the predicted value is not lactating.

In [54]:
X.iloc[0,:]

CurrentMilk    45.0
Previous       45.0
Fat             5.5
Protein         8.9
Days           21.0
Lactation       5.0
Name: 0, dtype: float64

In [55]:
x=np.array([89,89,3.9,3.9,149,2]).reshape(1,-1)

In [56]:
model1.predict(x)

c:\my drive\research work2\coding\env\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.14356603])

In [58]:
model2.predict(x)

c:\my drive\research work2\coding\env\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.85643397])

###  The value of lactating function is more than not lactating, therefore the predicted value is lactating.